$('.owl-carousel').owlCarousel({
    loop:true,
    margin:11,
    nav:true,
    autoplay:true,
    autoplaySpeed:1000,
    arrows:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
})
